language: ruby
script: ./script/cibuild
rvm:
  - 2.0
  - 2.1
  - 2.2
sudo: false
cache: bundler
notifications:
  email: false

env:
  global:
    MACHINE_USER_NAME: Hubot
    MACHINE_USER_EMAIL: hubot@example.com
